name: guided
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  google_maps: ^8.1.1
  google_maps_flutter: ^2.10.0
  place_picker: ^0.10.0
  place_picker_google: ^0.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
