// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIfjJDI6FHrnhqG3474gkaqxUdx0o-r2o',
    appId: '1:597062997841:web:e388e3e17daf8c3adc6570',
    messagingSenderId: '597062997841',
    projectId: 'fluttertest-1c0b8',
    authDomain: 'fluttertest-1c0b8.firebaseapp.com',
    storageBucket: 'fluttertest-1c0b8.firebasestorage.app',
    measurementId: 'G-GBTJ4QVWMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqXtoN8lYiLqrzEKcJlj8c7Td-ijoFcOo',
    appId: '1:597062997841:android:13b4c93ad98b02a5dc6570',
    messagingSenderId: '597062997841',
    projectId: 'fluttertest-1c0b8',
    storageBucket: 'fluttertest-1c0b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAHtJ9O0RcGlX9dsc7G3TLqm8oBkX6bWI',
    appId: '1:597062997841:ios:0cfd39b76d6e65acdc6570',
    messagingSenderId: '597062997841',
    projectId: 'fluttertest-1c0b8',
    storageBucket: 'fluttertest-1c0b8.firebasestorage.app',
    iosBundleId: 'com.example.guided',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAHtJ9O0RcGlX9dsc7G3TLqm8oBkX6bWI',
    appId: '1:597062997841:ios:0cfd39b76d6e65acdc6570',
    messagingSenderId: '597062997841',
    projectId: 'fluttertest-1c0b8',
    storageBucket: 'fluttertest-1c0b8.firebasestorage.app',
    iosBundleId: 'com.example.guided',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIfjJDI6FHrnhqG3474gkaqxUdx0o-r2o',
    appId: '1:597062997841:web:8e78f19f88cd0af2dc6570',
    messagingSenderId: '597062997841',
    projectId: 'fluttertest-1c0b8',
    authDomain: 'fluttertest-1c0b8.firebaseapp.com',
    storageBucket: 'fluttertest-1c0b8.firebasestorage.app',
    measurementId: 'G-2WE4G2ZT3C',
  );
}
